<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

class ClothingItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('clothing_items')->insert([
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/vaPHGsfn8Xga7V3DzlD8ihadcA5qL2zMZzpw2SRR.png'),
                'category_group' => 'Footwear',
                'category' => 'Sneakers',
                'color_group' => 'brights',
                'material' => 'patent leather',
                'pattern' => 'color-block',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'lace-up',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'sneakers',
                'height' => 'mid-top',
                'toe' => 'round toe',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/n7p4izhG0fSB7y04dCCRSaRu5BeCWoY0iGuOBDGX.png'),
                'category_group' => 'Footwear',
                'category' => 'Sneakers',
                'color_group' => 'neutrals',
                'material' => 'synthetic',
                'pattern' => 'color-block',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'lace-up',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'sneakers',
                'height' => 'low-top',
                'toe' => 'round toe',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/1YUVz4sVPUMOQZwv4zjvDK77wOLaXKaM9VTJKbZY.png'),
                'category_group' => 'Footwear',
                'category' => 'Sneakers',
                'color_group' => 'neutrals',
                'material' => 'synthetic',
                'pattern' => 'graphic',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'lace-up',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'sneakers',
                'height' => 'low-top',
                'toe' => 'round toe',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/vpEU0kpfk09XbOZ2roRBs4A01oY4gYQB2QSdQ8uj.png'),
                'category_group' => 'Tops',
                'category' => 'Button-down shirt',
                'color_group' => 'neutrals',
                'material' => 'cotton',
                'pattern' => 'solid',
                'style' => null,
                'fit' => 'regular',
                'length' => 'standard',
                'closure' => 'button',
                'sleeve' => 'short',
                'neckline' => 'collared',
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/gKge2bEor1Q2FQPiMcywpbKL5mk8KpKnzMO3RdpC.png'),
                'category_group' => 'Tops',
                'category' => 'Button-down shirt',
                'color_group' => 'darks',
                'material' => 'cotton',
                'pattern' => 'solid',
                'style' => null,
                'fit' => 'relaxed',
                'length' => 'standard',
                'closure' => 'button',
                'sleeve' => 'long',
                'neckline' => 'collared',
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/fsDYvGdEYljNKaZel66aPkDjoWqotxv26XQN3Dtr.png'),
                'category_group' => 'Tops',
                'category' => 'Button-down shirt',
                'color_group' => 'neutrals',
                'material' => 'cotton',
                'pattern' => 'batik',
                'style' => null,
                'fit' => 'regular',
                'length' => 'standard',
                'closure' => 'button',
                'sleeve' => 'short',
                'neckline' => 'collared',
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/n2gW6JEpIvyEZanNsLLsYcTlez8Tw8zzY11jfOTT.png'),
                'category_group' => 'Tops',
                'category' => 'Button-down shirt',
                'color_group' => 'neutrals',
                'material' => 'cotton',
                'pattern' => 'batik',
                'style' => null,
                'fit' => 'relaxed',
                'length' => 'standard',
                'closure' => 'button',
                'sleeve' => 'long',
                'neckline' => 'collared',
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/klvjM97rp8cmJmET5HpJJ0Tx3So4qeebYTUJVXX8.png'),
                'category_group' => 'Dresses & Rompers',
                'category' => 'Midi dress',
                'color_group' => 'neutrals',
                'material' => 'linen',
                'pattern' => 'solid',
                'style' => 'maxi',
                'fit' => null,
                'length' => 'midi',
                'closure' => 'pullover',
                'sleeve' => 'sleeveless',
                'neckline' => null,
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/7q659QlmQB3BMK0Njn9z9WxQdibTQzwINc84pHDT.png'),
                'category_group' => 'Dresses & Rompers',
                'category' => 'Mini dress',
                'color_group' => 'darks',
                'material' => 'cotton',
                'pattern' => 'solid',
                'style' => 'bodycon',
                'fit' => null,
                'length' => 'midi',
                'closure' => 'pullover',
                'sleeve' => 'sleeveless',
                'neckline' => null,
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/cbZuZ7L2mgjsNIDAlBKjHtOsV6lSGPb2ZAxff9QM.png'),
                'category_group' => 'Dresses & Rompers',
                'category' => 'Wrap dress',
                'color_group' => 'brights',
                'material' => 'cotton',
                'pattern' => 'solid',
                'style' => 'wrap',
                'fit' => null,
                'length' => 'midi',
                'closure' => 'tie',
                'sleeve' => 'sleeveless',
                'neckline' => null,
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/r6858XbNVWssXCxlYabLfO7XMWzxPglnHgYxcezo.png'),
                'category_group' => 'Bottoms',
                'category' => 'Dress pants',
                'color_group' => 'neutrals',
                'material' => 'wool',
                'pattern' => 'solid',
                'style' => null,
                'fit' => 'relaxed',
                'length' => 'full',
                'closure' => 'drawstring',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'slacks',
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/vD4ieRHBepqqEITC1E50qd5VEVQ9Bcb9UBmM09LK.png'),
                'category_group' => 'Bottoms',
                'category' => 'Denim shorts',
                'color_group' => 'neutrals',
                'material' => 'denim',
                'pattern' => 'solid',
                'style' => null,
                'fit' => 'relaxed',
                'length' => 'full',
                'closure' => 'drawstring',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'jeans',
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/81d1dfNilYFN6FQOj0pkeH2eDNAgZeAQkDDVdZJm.png'),
                'category_group' => 'Bottoms',
                'category' => 'Cargo pants',
                'color_group' => 'neutrals',
                'material' => 'cotton',
                'pattern' => 'camouflage',
                'style' => null,
                'fit' => 'relaxed',
                'length' => 'full',
                'closure' => 'drawstring',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'cargos',
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/BU7f70p6psfgLaLlDxVbRJRZk9JFEZ5L57uWBKXI.png'),
                'category_group' => 'Bottoms',
                'category' => 'Chino pants',
                'color_group' => 'neutrals',
                'material' => 'cotton',
                'pattern' => 'solid',
                'style' => null,
                'fit' => 'relaxed',
                'length' => 'full',
                'closure' => 'button',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'chinos',
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/pdQ0BHAP8Gr4WvknTyEciI7IYZgFOLW4K0B3M7Q2.png'),
                'category_group' => 'Tops',
                'category' => 'Jersey',
                'color_group' => 'pastels',
                'material' => 'cotton',
                'pattern' => 'striped',
                'style' => null,
                'fit' => 'regular',
                'length' => 'standard',
                'closure' => 'pullover',
                'sleeve' => 'long',
                'neckline' => 'crew',
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/konixG0D35sznZARvR6BbsYGXz37nzKpABhtWjCA.png'),
                'category_group' => 'Tops',
                'category' => 'T-shirt',
                'color_group' => 'pastels',
                'material' => 'cotton',
                'pattern' => 'graphic',
                'style' => null,
                'fit' => 'regular',
                'length' => 'standard',
                'closure' => 'pullover',
                'sleeve' => 'short',
                'neckline' => 'scoop',
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/8sjW04Uxe7fH06DeT9y5CgLaNrOliddHrSYY9HDH.png'),
                'category_group' => 'Footwear',
                'category' => 'Ankle boots',
                'color_group' => 'neutrals',
                'material' => 'suede',
                'pattern' => 'solid',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'lace-up',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'boots',
                'height' => 'mid-top',
                'toe' => 'open toe',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/PnglZyREfrmvJXXJAQwPio64nb4NgYr0fRUl9VxA.png'),
                'category_group' => 'Footwear',
                'category' => 'Heel pumps',
                'color_group' => 'neutrals',
                'material' => 'patent leather',
                'pattern' => 'color-block',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'slip-on',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'pumps',
                'height' => 'low-top',
                'toe' => 'round toe',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/uzx64BJGhFliDvzevKlpnfnBuOHpvPFAbtgBAZ9u.png'),
                'category_group' => 'Footwear',
                'category' => 'Sandals',
                'color_group' => 'brights',
                'material' => 'patent leather',
                'pattern' => 'animal print',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'buckle',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'pumps',
                'height' => 'low-top',
                'toe' => 'open toe',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/Z3ajnpGU0ceVk3u0rPMfiKlq58WZltem7HmeQ70i.png'),
                'category_group' => 'Skirts',
                'category' => 'A-line skirt',
                'color_group' => 'neutrals',
                'material' => 'cotton',
                'pattern' => 'solid',
                'style' => null,
                'fit' => 'regular',
                'length' => 'mini',
                'closure' => 'tie',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/vAxBVAAD0apl5MkUIR16hZesxWAEDcYb8RMMpiJb.png'),
                'category_group' => 'Skirts',
                'category' => 'Denim skirt',
                'color_group' => 'darks',
                'material' => 'denim',
                'pattern' => 'ombre',
                'style' => null,
                'fit' => 'regular',
                'length' => 'knee',
                'closure' => 'button',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/JAnXRqiWINAoImQmxqz5d8NXTYOVDpOrg7aru5XU.png'),
                'category_group' => 'Cultural & Traditional Attire',
                'category' => 'Lederhosen pants',
                'color_group' => 'neutrals',
                'material' => 'leather',
                'pattern' => 'solid',
                'style' => null,
                'fit' => 'fitted',
                'length' => 'knee',
                'closure' => 'knee',
                'sleeve' => 'short',
                'neckline' => 'wrap',
                'insulation' => null,
                'type' => null,
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/4TNZ7pHpeafMtO13UyWAROILU0Uz67hM09kr2Wlx.png'),
                'category_group' => 'Accessories & Bags',
                'category' => 'Bow tie',
                'color_group' => 'neutrals',
                'material' => 'plastic',
                'pattern' => 'graphic',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'belt',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'belt',
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],



            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/LpVHVgqMl7W90kgtY705MR6L52X0wUm92OvARgGX.png'),
                'category_group' => 'Accessories & Bags',
                'category' => 'Earrings',
                'color_group' => 'neutrals',
                'material' => 'gold',
                'pattern' => 'paisley',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'handbag',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'handbag',
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/HTv0xecOz5KWcHo1DnamttlGDJDztkPgMx9rFsJU.png'),
                'category_group' => 'Accessories & Bags',
                'category' => 'Earrings',
                'color_group' => 'brights',
                'material' => 'silver',
                'pattern' => 'solid',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'clutch',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'clutch',
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],



            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/NPb0qmtjKm3hwoq1WXtpNM9LkiMnicdtygd17VWJ.png'),
                'category_group' => 'Accessories & Bags',
                'category' => 'Earrings',
                'color_group' => 'brights',
                'material' => 'silver',
                'pattern' => 'paisley',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'handbag',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'handbag',
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'user_id' => 1,
                'image_url' => Storage::url('clothing_images/JipLKIo66HPIa4BZBiYtoGqIUn2i5sguw40XPnlS.png'),
                'category_group' => 'Accessories & Bags',
                'category' => 'Earrings',
                'color_group' => 'metallics',
                'material' => 'gold',
                'pattern' => 'paisley',
                'style' => null,
                'fit' => null,
                'length' => null,
                'closure' => 'sunglasses',
                'sleeve' => null,
                'neckline' => null,
                'insulation' => null,
                'type' => 'sunglasses',
                'height' => null,
                'toe' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],







        ]);
    }
}
